version: '3'

services:
    stimu-frontend:
        image: node:14.4.0-alpine
        working_dir: /usr/src/app
        command: sh -c "npm install && npm start"
        env_file:
            - .env.dev
        volumes:
            - "../stimulaatio-frontend:/usr/src/app"

    stimu-backend:
        image: python:3
        working_dir: /usr/src/app
        command: sh -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - "../stimulaatio-backend:/usr/src/app"
            - "admin_static:/usr/src/api/static"
        env_file:
            - .env.dev
        environment:
            - DJANGO_DEBUG=1

    stimu-db:
        image: postgres
        volumes:
            - "dbdata:/var/lib/postgresql/data"
        env_file:
            - .env.dev

    caddy:
        image: caddy
        volumes:
            - "./Caddyfile:/etc/caddy/Caddyfile"
            - "./caddy_data:/data"
            - "admin_static:/django_static"
        ports:
            - 80:80
            - 433:433
            - 3000:3000

volumes:
  dbdata:
  admin_static:
