FROM python:3

# Create api directory
RUN mkdir -p /usr/src/api
WORKDIR /usr/src/api

# Clone stuff from GitHub
RUN apk update && apk add git
RUN git clone https://github.com/Qaapu/stimulaatio-backend.git
WORKDIR /usr/src/api/stimulaatio-backend

# Install api dependencies
RUN pip install -r requirements.txt

# Run api
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
