version: '3'

services:
    stimu-frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        image: stimu-frontend
        ports:
            - 5001:5000

    stimu-backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        image: stimu-backend
        ports:
            - 5002:8000
        links:
            - stimu-db
        depends_on:
            - migration
        environment:
            - STIMU_DB=stimu-db
        env_file:
            - .env.production.local

    stimu-db:
        image: postgres

    migration:
        image: stimu-backend
        command: python manage.py migrate --noinput
        depends_on:
            - stimu-db
        environment:
            - STIMU_DB=stimu-db
