version: '3'

services:
    stimu-frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        image: stimu-frontend
        ports:
            - 5001:5000
        environment:
            - REACT_APP_BACKEND=34.253.76.46:5002
        volumes:
            - build:/usr/src/app/stimulaatio-frontend/build

    stimu-backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        image: stimu-backend
        ports:
            - 5002:8000
        links:
            - stimu-db
        environment:
            - STIMU_DB=stimu-db

    stimu-db:
        image: postgres
