version: '3'

services:
    stimu-frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        image: stimu-frontend
        ports:
            - 5001:5000

    stimu-backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        image: stimu-backend
        ports:
            - 5002:8000
        links:
            - stimu-db
        depends_on:
            - migration
        env_file:
            - .env.production.local

    stimu-db:
        image: postgres
        volumes:
            - "dbdata:/var/lib/postgresql/data"
        env_file:
            - .env.production.local

volumes:
  dbdata:
