version: '3'

services:
    stimu-frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        image: stimu-frontend
        ports:
            - 81:5000

    stimu-backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        image: stimu-backend
        ports:
            - 5002:8000
        links:
            - stimu-db
        env_file:
            - .env.production.local

    stimu-db:
        image: postgres
        volumes:
            - "dbdata:/var/lib/postgresql/data"
        env_file:
            - .env.production.local

    nginx:
        image: nginx
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./nginx.d/data/nginx:/etc/nginx/conf.d
          - ./nginx.d/data/conf:/etc/letsencrypt
          - ./nginx.d/data/certbot/www:/var/www/certbot
        network_mode: "host"
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    certbot:
        image: certbot/certbot
        volumes:
          - ./nginx.d/data/conf:/etc/letsencrypt
          - ./nginx.d/data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  dbdata:

